const data = [
    {
        id: '1',
        brand: 'Apple',
        model: 'IPhone 13',
        count: '53',
        year: '2021',
        producer: 'USA',
        color: 'pink',
        size: '256',
        price: '1100',
        img: './assets/images/iphone-13-pink.png',
        favorite: true,
    },
    {
        id: '2',
        brand: 'Apple',
        model: 'IPhone 13',
        count: '26',
        year: '2021',
        producer: 'USA',
        color: 'green',
        size: '128',
        price: '1150',
        img: './assets/images/iphone-13-green.png',
        favorite: false,
    },
    {
        id: '3',
        brand: 'Apple',
        model: 'IPhone 13 Pro',
        count: '23',
        year: '2021',
        producer: 'USA',
        color: 'green',
        size: '256',
        price: '1470',
        img: './assets/images/iphone-13-pro-green.png',
        favorite: false,
    },
    {
        id: '4',
        brand: 'Apple',
        model: 'IPhone 13 Pro',
        count: '81',
        year: '2021',
        producer: 'USA',
        color: 'blue',
        size: '256',
        price: '1420',
        img: './assets/images/iphone-13-pro-blue.png',
        favorite: true,
    },
    {
        id: '5',
        brand: 'Apple',
        model: 'IPhone 12',
        count: '12',
        year: '2020',
        producer: 'USA',
        color: 'red',
        size: '64',
        price: '780',
        img: './assets/images/iphone-12-red.png',
        favorite: false,
    },
    {
        id: '6',
        brand: 'Apple',
        model: 'IPhone 12',
        count: '48',
        year: '2020',
        producer: 'USA',
        color: 'white',
        size: '128',
        price: '930',
        img: './assets/images/iphone-12-white.png',
        favorite: true,
    },
    {
        id: '7',
        brand: 'Apple',
        model: 'IPhone 12',
        count: '35',
        year: '2020',
        producer: 'USA',
        color: 'black',
        size: '128',
        price: '910',
        img: './assets/images/iphone-12-black.png',
        favorite: false,
    },
    {
        id: '8',
        brand: 'Samsung',
        model: 'Galaxy S20 FE',
        count: '7',
        year: '2020',
        producer: 'Vietnam',
        color: 'blue',
        size: '128',
        price: '640',
        img: './assets/images/samsung-s20-blue.png',
        favorite: false,
    },
    {
        id: '9',
        brand: 'Samsung',
        model: 'Galaxy A12',
        count: '10',
        year: '2021',
        producer: 'Vietnam',
        color: 'blue',
        size: '64',
        price: '250',
        img: './assets/images/samsung-a12-blue.png',
        favorite: false,
    },
    {
        id: '10',
        brand: 'Samsung',
        model: 'Galaxy S21 FE',
        count: '35',
        year: '2022',
        producer: 'Poland',
        color: 'pink',
        size: '256',
        price: '760',
        img: './assets/images/samsung-s21-pink.png',
        favorite: true,
    },
    {
        id: '11',
        brand: 'Samsung',
        model: 'Galaxy S22',
        count: '19',
        year: '2022',
        producer: 'Poland',
        color: 'pink',
        size: '512',
        price: '1360',
        img: './assets/images/samsung-s22-pink.png',
        favorite: true,
    },
    {
        id: '12',
        brand: 'Samsung',
        model: 'Galaxy S22+',
        count: '4',
        year: '2022',
        producer: 'Vietnam',
        color: 'green',
        size: '256',
        price: '1910',
        img: './assets/images/samsung-s22+-green.png',
        favorite: false,
    },
    {
        id: '13',
        brand: 'Samsung',
        model: 'Galaxy A52',
        count: '71',
        year: '2021',
        producer: 'Vietnam',
        color: 'black',
        size: '128',
        price: '360',
        img: './assets/images/samsung-a52-black.png',
        favorite: true,
    },
    {
        id: '14',
        brand: 'Xiaomi',
        model: '11 Lite',
        count: '27',
        year: '2021',
        producer: 'China',
        color: 'black',
        size: '128',
        price: '380',
        img: './assets/images/xiaomi-11-lite.png',
        favorite: false,
    },
    {
        id: '15',
        brand: 'Xiaomi',
        model: 'Redmi Note 8',
        count: '73',
        year: '2021',
        producer: 'China',
        color: 'blue',
        size: '128',
        price: '310',
        img: './assets/images/xiaomi-note-8.png',
        favorite: true,
    },
    {
        id: '16',
        brand: 'Xiaomi',
        model: 'Mi 11 Ultra',
        count: '16',
        year: '2021',
        producer: 'China',
        color: 'white',
        size: '512',
        price: '1120',
        img: './assets/images/xiaomi-mi-11-ultra.png',
        favorite: true,
    },
    {
        id: '17',
        brand: 'Xiaomi',
        model: 'Note 10s',
        count: '22',
        year: '2021',
        producer: 'China',
        color: 'white',
        size: '128',
        price: '290',
        img: './assets/images/xiaomi-note-10s.png',
        favorite: false,
    },
    {
        id: '18',
        brand: 'Xiaomi',
        model: '11T',
        count: '13',
        year: '2021',
        producer: 'China',
        color: 'blue',
        size: '256',
        price: '520',
        img: './assets/images/xiaomi-11t.png',
        favorite: false,
    },
    {
        id: '19',
        brand: 'Apple',
        model: 'IPhone SE',
        count: '45',
        year: '2020',
        producer: 'USA',
        color: 'red',
        size: '128',
        price: '490',
        img: './assets/images/iphone-se-red.png',
        favorite: true,
    },
    {
        id: '20',
        brand: 'Apple',
        model: 'IPhone SE',
        count: '16',
        year: '2020',
        producer: 'USA',
        color: 'white',
        size: '64',
        price: '440',
        img: './assets/images/iphone-se-white.png',
        favorite: true,
    },
    {
        id: '21',
        brand: 'Apple',
        model: 'IPhone 11',
        count: '5',
        year: '2019',
        producer: 'USA',
        color: 'green',
        size: '64',
        price: '640',
        img: './assets/images/iphone-11-green.png',
        favorite: false,
    },
    {
        id: '22',
        brand: 'Apple',
        model: 'IPhone 11',
        count: '25',
        year: '2019',
        producer: 'USA',
        color: 'white',
        size: '128',
        price: '740',
        img: './assets/images/iphone-11-white.png',
        favorite: true,
    },
    {
        id: '23',
        brand: 'Apple',
        model: 'IPhone 12 Max',
        count: '3',
        year: '2020',
        producer: 'USA',
        color: 'blue',
        size: '128',
        price: '1240',
        img: './assets/images/iphone-12-pro-max-blue.png',
        favorite: false,
    },
    {
        id: '24',
        brand: 'Apple',
        model: 'IPhone 12 mini',
        count: '46',
        year: '2020',
        producer: 'USA',
        color: 'red',
        size: '256',
        price: '910',
        img: './assets/images/iphone-12-mini-red.png',
        favorite: true,
    },
];

export default data;
